apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm-backend
  template:
    metadata:
      labels:
        app: farm-backend
    spec:
      containers:
      - name: backend
        image: nigethadocker/farm-backend:latest # Unga backend image name
        ports:
        - containerPort: 5000