apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: farm-app
  template:
    metadata:
      labels:
        app: farm-app
    spec:
      containers:
      - name: farm-app-container
        image: farm-management-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80