apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farm-app
  template:
    metadata:
      labels:
        app: farm-app
    spec:
      containers:
      - name: farm-app-container
        image: nigethadocker/farm-management-app:latest
        ports:
        - containerPort: 80
